# Jekyll-style configuration for D292 WGU files

# Directory defaults for all D292 files
defaults:
  categories: ["WGU" ]
  tags: ["wgu", "d292"]
  author: "John Mortensen"

# File-specific overrides
files:
  Plagiarism-WGU-SGM2-Task1-Ideation-Higher-Level-Education:
    title: "D292 Task 1: Digital Citizenship Ideation"
    description: "WGU D292 assessment focusing on digital citizenship education ideation phase"
    permalink: "/wgu/d292/task1-ideation/"

  Plagiarism-WGU-SGM2-Task2-Storyboard-Higher-Level-Education:
    title: "D292 Task 2: Digital Citizenship Storyboard"
    description: "WGU D292 assessment with storyboard design for digital citizenship education"
    permalink: "/wgu/d292/task2-storyboard/"

  Plagiarism-WGU-SGM2-Task3-Mockup-Higher-Level-Education:
    title: "D292 Task 3: Digital Citizenship Mockup"
    description: "WGU D292 assessment with interactive mockup for digital citizenship education"
    permalink: "/wgu/d292/task3-mockup/"

  Plagiarism-WGU-SGM2-Task4-Test-Plan-Higher-Level-Education:
    title: "D292 Task 4: Digital Citizenship Test Plan"
    description: "WGU D292 assessment with comprehensive test plan for digital citizenship education"
    permalink: "/wgu/d292/task4-test-plan/"